tunnel: nekodesu
credentials-file: /etc/cloudflared/credentials.json
origincert: /etc/cloudflared/cert.pem

ingress:
  - hostname: nekodesu.dogbeach.club
    service: http://web:80
  - service: http_status:404
